server:
  port: 7777 #端口号
 
spring:
  application:
    name: service-zuul  #服务注册中心测试名

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1 
  
 
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

zuul:
  host:
        connect-timeout-millis: 3000
        socket-timeout-millis: 3000
  routes:
    api-a:
      path: /studentServer/**
      serviceId: studentServer  #如果是/student/**路径下的请求，则跳转到student
    api-b:
      path: /clazzServer/**
      serviceId: clazzServer  #如果是/clazz/**路径下的请求，则跳转到clazz
    api-c:
      path: /gradeServer/**
      serviceId: gradeServer  #如果是/grade/**路径下的请求，则跳转到grade

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6666/eureka/  #服务注册中心